consul:
    image: qnib/alpn-consul
    hostname: consul
    container_name: ${USER}_consul
    dns: 127.0.0.1
    ports:
     - 8500
    environment:
     - DC_NAME=dc1
     - CONSUL_BOOTSTRAP=true

gocd-server:
    hostname: gocd-server
    container_name: ${USER}_gocd-server
    image: qnib/gocd-server
    dns: 127.0.0.1
    ports:
     - 8153
    environment:
     - DC_NAME=dc1
     - SUPERVISOR_SKIP_SRV=gocd-server
    links:
     - consul:consul
    volumes:
     - ./config/:/config/
     - ./serverBackups/:/opt/go-server/artifacts/serverBackups/

gocd-agent1:
    hostname: gocd-agent1
    container_name: ${USER}_gocd-agent1
    image: qnib/alpn-gocd-agent
    dns: 127.0.0.1
    environment:
     - DC_NAME=dc1
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    links:
     - consul:consul

gocd-agent2:
    hostname: gocd-agent2
    container_name: ${USER}_gocd-agent2
    image: qnib/alpn-gocd-agent
    dns: 127.0.0.1
    environment:
     - DC_NAME=dc1
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    links:
     - consul:consul

gocd-agent3:
    hostname: gocd-agent3
    container_name: ${USER}_gocd-agent3
    image: qnib/alpn-gocd-agent
    dns: 127.0.0.1
    environment:
     - DC_NAME=dc1
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    links:
     - consul:consul
