version: '2'
services:
  consul:
    image: qnib/alpn-consul
    hostname: consul
    container_name: consul
    networks:
     - gocd
    ports:
     - 8500:8500
    environment:
     - DC_NAME=gocd-dc
     - CONSUL_BOOTSTRAP_EXPECTED=1

  gocd-server:
    hostname: gocd-server
    container_name: gocd-server
    image: qnib/gocd-server:d12
    dns:
      - consul
      - 8.8.8.8
    networks:
     - gocd
    ports:
     - 8153:8153
    environment:
     - DC_NAME=gocd-dc
     - GOCD_SERVER_CLEAN_WORKSPACE=false
     - CONSUL_CLUSTER_IPS=consul
    volumes:
     - ./serverBackups/:/opt/go-server/artifacts/serverBackups/

  gocd-agent1:
    hostname: gocd-agent1
    container_name: gocd-agent1
    image: qnib/alpn-gocd-agent
    networks:
     - gocd
    dns:
      - consul
      - 8.8.8.8
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - DC_NAME=gocd-dc
     - GO_SERVER=gocd-server
     - GOCD_LOCAL_DOCKERENGINE=false
     - CONSUL_CLUSTER_IPS=consul

networks:
  gocd:
    driver: bridge
