consul:
    image: qnib/consul
    hostname: consul
    container_name: consul
    dns: 127.0.0.1
    ports:
     - "8500:8500"
    environment:
     - DC_NAME=dc1
     - CONSUL_BOOTSTRAP=true

gocd-server:
    hostname: gocd-server
    container_name: gocd-server
    image: qnib/gocd-server
    dns: 127.0.0.1
    ports:
     - 8153:8153
     - 8154:8154
    environment:
     - DC_NAME=dc1
    links:
     - consul:consul

gocd-agent1:
    hostname: gocd-agent1
    container_name: gocd-agent1
    image: qnib/alpn-gocd-agent
    dns: 127.0.0.1
    environment:
     - DC_NAME=dc1
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    links:
     - consul:consul

